// @ts-nocheck
// src/lib/fallback.ts
export const fallbackResorts = [
  { id: '1', name: 'Valle Nevado', country: 'Chile', region: 'south_america', description_es: 'El centro de esquí más grande de Sudamérica en los Andes chilenos.', description_en: 'The largest ski resort in South America in the Chilean Andes.', difficulty: 'intermediate', altitude_base_m: 2860, altitude_peak_m: 3670, total_runs: 40, total_lifts: 14, season_start: 'Junio', season_end: 'Octubre', avg_snowfall_cm: 350, image_url: 'https://images.unsplash.com/photo-1551524559-8af4e6624178?w=800', latitude: -33.35, longitude: -70.25, avg_daily_cost_usd: 180, highlights: ['Heliesquí', 'Tres centros interconectados'] },
  { id: '2', name: 'Portillo', country: 'Chile', region: 'south_america', description_es: 'Resort legendario con la Laguna del Inca.', description_en: 'Legendary resort with Inca Lake.', difficulty: 'advanced', altitude_base_m: 2590, altitude_peak_m: 3348, total_runs: 35, total_lifts: 14, season_start: 'Junio', season_end: 'Octubre', avg_snowfall_cm: 300, image_url: 'https://images.unsplash.com/photo-1565992441121-4367c2967103?w=800', latitude: -32.84, longitude: -70.13, avg_daily_cost_usd: 250, highlights: ['Laguna del Inca', 'Todo incluido'] },
  { id: '3', name: 'Cerro Catedral', country: 'Argentina', region: 'south_america', description_es: 'El más grande en pistas, en Bariloche.', description_en: 'Largest by terrain, in Bariloche.', difficulty: 'intermediate', altitude_base_m: 1030, altitude_peak_m: 2100, total_runs: 120, total_lifts: 39, season_start: 'Junio', season_end: 'Octubre', avg_snowfall_cm: 400, image_url: 'https://images.unsplash.com/photo-1483728642387-6c3bdd6c93e5?w=800', latitude: -41.16, longitude: -71.44, avg_daily_cost_usd: 120, highlights: ['Mayor área esquiable', 'Bariloche'] },
  { id: '4', name: 'Aspen Snowmass', country: 'USA', region: 'north_america', description_es: 'Cuatro montañas legendarias en Colorado.', description_en: 'Four legendary mountains in Colorado.', difficulty: 'advanced', altitude_base_m: 2422, altitude_peak_m: 3813, total_runs: 337, total_lifts: 47, season_start: 'Noviembre', season_end: 'Abril', avg_snowfall_cm: 450, image_url: 'https://images.unsplash.com/photo-1605540436563-5bca919ae766?w=800', latitude: 39.19, longitude: -106.82, avg_daily_cost_usd: 350, highlights: ['Cuatro montañas', 'Gastronomía premium'] },
  { id: '5', name: 'Whistler Blackcomb', country: 'Canada', region: 'north_america', description_es: 'El resort más grande de Norteamérica.', description_en: 'The largest resort in North America.', difficulty: 'intermediate', altitude_base_m: 675, altitude_peak_m: 2284, total_runs: 200, total_lifts: 37, season_start: 'Noviembre', season_end: 'Mayo', avg_snowfall_cm: 550, image_url: 'https://images.unsplash.com/photo-1530053969600-caed2596d242?w=800', latitude: 50.12, longitude: -122.96, avg_daily_cost_usd: 280, highlights: ['Peak 2 Peak Gondola', 'Sede olímpica'] },
  { id: '6', name: 'Chamonix', country: 'France', region: 'europe', description_es: 'Capital mundial del alpinismo bajo el Mont Blanc.', description_en: 'World capital of mountaineering under Mont Blanc.', difficulty: 'advanced', altitude_base_m: 1035, altitude_peak_m: 3842, total_runs: 170, total_lifts: 66, season_start: 'Diciembre', season_end: 'Abril', avg_snowfall_cm: 400, image_url: 'https://images.unsplash.com/photo-1522926193341-e9ffd686c60f?w=800', latitude: 45.92, longitude: 6.87, avg_daily_cost_usd: 250, highlights: ['Mont Blanc', 'Vallée Blanche'] },
  { id: '7', name: 'Zermatt', country: 'Switzerland', region: 'europe', description_es: 'Esquí todo el año con vistas al Matterhorn.', description_en: 'Year-round skiing with Matterhorn views.', difficulty: 'intermediate', altitude_base_m: 1620, altitude_peak_m: 3883, total_runs: 200, total_lifts: 52, season_start: 'Noviembre', season_end: 'Abril', avg_snowfall_cm: 450, image_url: 'https://images.unsplash.com/photo-1531366936337-7c912a4589a7?w=800', latitude: 46.02, longitude: 7.75, avg_daily_cost_usd: 400, highlights: ['Matterhorn', 'Esquí todo el año'] },
  { id: '8', name: 'Niseko', country: 'Japan', region: 'asia', description_es: 'Famoso por su nieve polvo y onsen.', description_en: 'Famous for powder snow and onsen.', difficulty: 'intermediate', altitude_base_m: 260, altitude_peak_m: 1308, total_runs: 75, total_lifts: 27, season_start: 'Diciembre', season_end: 'Mayo', avg_snowfall_cm: 1500, image_url: 'https://images.unsplash.com/photo-1542272201-b1ca555f8505?w=800', latitude: 42.86, longitude: 140.70, avg_daily_cost_usd: 250, highlights: ['Nieve polvo', 'Onsen tradicional'] },
];

export const fallbackPackage = {
  resort_name: 'Valle Nevado',
  resort_country: 'Chile',
  resort_region: 'south_america',
  resort_description: 'El centro de esquí más grande de Sudamérica, ubicado a solo 60km de Santiago.',
  difficulty_match: 'intermediate',
  trip_duration_days: 7,
  flight: { airline: 'LATAM Airlines', departure_city: 'Santiago', arrival_city: 'Santiago (transfer)', outbound_date: '2025-07-15', outbound_time: '—', return_date: '2025-07-22', return_time: '—', price_usd: 0, cabin_class: 'N/A', stops: 0, duration_hours: 0 },
  hotel: { name: 'Hotel Valle Nevado', stars: 4, check_in: '2025-07-15', check_out: '2025-07-22', room_type: 'Doble Vista Montaña', price_per_night: 220, total_price: 1540, distance_to_slopes: 'Ski-in/Ski-out', amenities: ['Spa', 'Restaurant', 'Ski Storage', 'WiFi'] },
  ski_pass: { type: 'Full Area Pass', duration_days: 6, includes_insurance: true, price_usd: 320, coverage: 'Todos los andariveles' },
  equipment: { items: [{ type: 'Esquís', category: 'Performance', price_per_day: 35 }, { type: 'Botas', category: 'Comfort', price_per_day: 20 }, { type: 'Bastones', category: 'Standard', price_per_day: 8 }, { type: 'Casco', category: 'Safety', price_per_day: 12 }], total_per_day: 75, total_price: 450, rental_days: 6 },
  transfers: { type: 'Shuttle Privado', airport_to_resort: 65, resort_to_airport: 65, total_price: 130 },
  lessons: { available: true, type: 'Clase grupal', hours_per_day: 2, days: 3, price_usd: 180 },
  cost_breakdown: { flights: 0, hotel: 1540, ski_pass: 320, equipment: 450, transfers: 130, lessons: 180, meals_estimate: 350, insurance: 60, subtotal: 3030, taxes_and_fees: 303, total_per_person_usd: 3333 },
  highlights: ['Ski-in/Ski-out', 'Spa incluido', 'A 60km de Santiago'],
  best_for: 'Ideal para esquiadores intermedios que buscan comodidad cerca de Santiago.',
  weather_forecast: 'Temperaturas entre -5°C y 5°C con nieve frecuente en julio.'
};